name: "Publish New Draft Version"

on:
  push:
    tags:
      - "draft-*"

jobs:
  build:
    name: "Publish New Draft Version"
    runs-on: ubuntu-latest
    steps:
    - name: "Checkout"
      uses: actions/checkout@v3

    # See https://github.com/actions/checkout/issues/290
    - name: "Get Tag Annotations"
      run: git fetch -f origin ${{ github.ref }}:${{ github.ref }}

    - name: "Setup"
      id: setup
      run: date -u "+::set-output name=date::%FT%T"

    # Check out the SD-JWT tooling
    - name: "Checkout SD-JWT library and tooling"
      uses: actions/checkout@v3
      with:
        repository: "danielfett/sd-jwt"
        path: "sd-jwt"

    # Install the SD-JWT tooling using pip
    - name: "Install SD-JWT tooling"
      run: |
        cd sd-jwt
        python3 -m pip install --upgrade pip
        python3 -m pip install --upgrade .

    # Build the local examples
    - name: "Build local examples"
      run: |
        cd examples
        python3 ../sd-jwt/scripts/generate.py example

    - name: "Caching"
      uses: actions/cache@v3
      with:
        path: |
          .refcache
          .venv
          .gems
          node_modules
          .targets.mk
        key: i-d-${{ steps.setup.outputs.date }}
        restore-keys: i-d-

    - name: "Build Drafts"
      uses: martinthomson/i-d-template@v1
      with:
        token: ${{ github.token }}

    - name: "Upload to Datatracker"
      uses: martinthomson/i-d-template@v1
      with:
        make: upload

    - name: "Archive Submitted Drafts"
      uses: actions/upload-artifact@v2
      with:
        path: "draft-*-[0-9][0-9].xml"
